---
- name: Deploy Dockerized Webapp
  hosts: app_host
  become: yes
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy Docker Compose file
      copy:
        src: files/docker-compose.yml
        dest: /opt/app/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Stop and remove existing containers
      command: docker-compose -f /opt/app/docker-compose.yml down
      ignore_errors: yes
      changed_when: false

    - name: Pull latest images
      command: docker-compose -f /opt/app/docker-compose.yml pull

    - name: Start containers
      command: docker-compose -f /opt/app/docker-compose.yml up -d

    - name: Verify containers are running
      command: docker ps
      register: docker_ps
      changed_when: false

    - debug:
        var: docker_ps.stdout_lines