---
- name: Deploy Dockerized Webapp
  hosts: ec2
  become: yes
  tasks:
    - name: Install Docker and dependencies
      include_tasks: install_docker.yml

    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy Docker Compose file
      copy:
        src: files/docker-compose.yml
        dest: /opt/app/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Stop and remove existing containers
      command: docker compose -f /opt/app/docker-compose.yml down
      ignore_errors: yes
      changed_when: false

    - name: Pull latest images
      command: docker compose -f /opt/app/docker-compose.yml pull

    - name: Start containers
      command: docker compose -f /opt/app/docker-compose.yml up -d
      environment:
        COMPOSE_HTTP_TIMEOUT: 300

    - name: Verify containers are running
      command: docker ps
      register: docker_ps
      changed_when: false
      retries: 3
      delay: 10