---
- hosts: app_host
  become: yes
  tasks:
    # ─── Install prerequisites ───────────────────────────
    - name: Update APT cache & install base packages
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    # ─── Docker repository & key ─────────────────────────
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    # ─── Install Docker CE and the Compose plugin ────────
    - name: Install Docker + Compose plugin
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    # ─── Post-install tweaks ─────────────────────────────
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable & start Docker service
      service:
        name: docker
        state: started
        enabled: yes
