name: build-scan-push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                 # e.g. us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  FRONTEND_REPO: ${{ secrets.ECR_REPO_FRONTEND }}       # e.g. my-frontend
  BACKEND_REPO:  ${{ secrets.ECR_REPO_BACKEND }}        # e.g. my-backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # needed for OIDC; keep if you switch to role-based auth
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- AWS auth & ECR login ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------- Build images ----------
      - name: Set image tags
        id: vars
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "FRONT_TAG=${ECR_REGISTRY}/${FRONTEND_REPO}:${SHA}" >> $GITHUB_OUTPUT
          echo "BACK_TAG=${ECR_REGISTRY}/${BACKEND_REPO}:${SHA}"  >> $GITHUB_OUTPUT

      - name: Build frontend image
        run: docker build -t ${{ steps.vars.outputs.FRONT_TAG }} ./frontend

      - name: Build backend image
        run: docker build -t ${{ steps.vars.outputs.BACK_TAG }}  ./backend

      # ---------- Trivy scans (non-blocking) ----------
      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref:  ${{ steps.vars.outputs.FRONT_TAG }}
          exit-code: 0                 # do NOT fail the job
          ignore-unfixed: true         # suppress unfixed issues

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref:  ${{ steps.vars.outputs.BACK_TAG }}
          exit-code: 0
          ignore-unfixed: true

      # ---------- Push to ECR ----------
      - name: Push images to ECR
        run: |
          docker push ${{ steps.vars.outputs.FRONT_TAG }}
          docker push ${{ steps.vars.outputs.BACK_TAG }}
